# Importing modules

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu116


# Introduction to Tensors


## Creating tensors

Pytorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html 

In [199]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [200]:
# Tensor dimension
scalar.ndim

0

In [201]:
# Get tensor back as Python int 
scalar.item()

7

In [202]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [203]:
# Tensor dimension
vector.ndim

1

In [204]:
vector.shape

torch.Size([2])

In [205]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [206]:
MATRIX.ndim

2

In [207]:
MATRIX.shape

torch.Size([2, 2])

In [208]:
MATRIX[1]

tensor([ 9, 10])

In [209]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [210]:
TENSOR.ndim

3

In [211]:
TENSOR.shape

torch.Size([1, 3, 3])

In [212]:
# This is our size 1 in torch.Size([1, 3, 3])
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [213]:
# Create a random tensor of shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8038, 0.8669, 0.1415, 0.1050],
        [0.9981, 0.7891, 0.4596, 0.0741],
        [0.2034, 0.1180, 0.6373, 0.0976]])

In [214]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # Colour channel, Height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [215]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [216]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [217]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

Torch arange - https://pytorch.org/docs/stable/generated/torch.arange.html

In [218]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [219]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

PyTorch Tensor datatypes - https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [220]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatyoe is the tensor (r.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [221]:
float_32_tensor.dtype

torch.float32

In [222]:
# Define ne tensor with datatype float 16 and same values like in other tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [223]:
float_16_tensor * float_32_tensor
# even when we multiply 2 different datatype we won't get any error but we will get a higher datatype 

tensor([ 9., 36., 81.])

In [224]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [225]:
# Check if we get error mul int with float
int_32_tensor * float_32_tensor


tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to get  datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [226]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6305, 0.2857, 0.5269, 0.9702],
        [0.2296, 0.5748, 0.6351, 0.5052],
        [0.9594, 0.0290, 0.1142, 0.2829]])

In [227]:
# Find out details about some tensor
print(some_tensor,'-'*50,sep='\n')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}\nAlso you can use size() function: {some_tensor.size()}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.6305, 0.2857, 0.5269, 0.9702],
        [0.2296, 0.5748, 0.6351, 0.5052],
        [0.9594, 0.0290, 0.1142, 0.2829]])
--------------------------------------------------
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Also you can use size() function: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [228]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [229]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [230]:
tensor

tensor([1, 2, 3])

In [231]:
# Subtract 10 
tensor - 10

tensor([-9, -8, -7])

In [232]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
# It's doing same thing like tensor * 10

tensor([10, 20, 30])

In [233]:
# Same thing for add and so on
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

Matrix multiplication side with animation - http://matrixmultiplication.xyz/

In [234]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [235]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [236]:
%%time
# Time test
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 804 µs


In [237]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 202 µs, sys: 36 µs, total: 238 µs
Wall time: 149 µs


tensor(14)

### One of the most common errors in deep learining: shape errors

In [238]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

try:
    torch.mm(tensor_A, tensor_B) # torch.mm == torch.matmul
except RuntimeError:
    pass

In [239]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shpae issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [240]:
tensor_A.T, tensor_A.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [241]:
tensor_A, tensor_A.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [242]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_a = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_a = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [243]:
 # Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [244]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [245]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [246]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [247]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

---
### argmin()

In [248]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [249]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [250]:
x[0]

tensor(1)

---
### argmax()

In [251]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [252]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shpae but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a targer tensor
* Premute - return a view of the input with dimiensions permuted (swapped) in a certain way

In [281]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [302]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [283]:
# Change the view 
z = x.view(1, 9)
z, z.shape

# Result is the same as with reshape() function, but view() sharing same memory cell with the original tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [289]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 5., 3., 4., 5., 6., 7., 8., 9.]))

In [297]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.]])

In [299]:
# Vstack
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.],
        [5., 5., 3., 4., 5., 6., 7., 8., 9.]])

In [300]:
# Hstack
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked

tensor([5., 5., 3., 4., 5., 6., 7., 8., 9., 5., 5., 3., 4., 5., 6., 7., 8., 9.,
        5., 5., 3., 4., 5., 6., 7., 8., 9., 5., 5., 3., 4., 5., 6., 7., 8., 9.])

In [313]:
# torck.squeeze() - removes all single dimensions from tensors
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 5., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [318]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 5., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 5., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [321]:
# torch.permute - rearranges the dimesnions of target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
# Let's make colour_channel as a first dim
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [330]:
x_original[0, 0, 0] = 928374
# This will result on x_permuted, because they are sharing memory cell
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(928374.), tensor(928374.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [331]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [333]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [337]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [339]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [342]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [344]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [346]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [348]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [352]:
# Index on x to return 9
print(f'Index on x to return 9: {x[0, 2, 2]}')

# Index on x to return 3, 6, 9
print(f'Index on x to return 3, 6, 9: {x[:, :, 2]}')

Index on x to return 9: 9
Index on x to return 3, 6, 9: tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [355]:
# NumPy array to tensor

array = np.arange(1.0, 8.0) # Default datatype is float64
tensor = torch.from_numpy(array) # Default datatype is float32 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [356]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [358]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [360]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

**Torch reproducibility** - https://pytorch.org/docs/stable/notes/randomness.html

In [33]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B) 
print(random_tensor_A == random_tensor_B)

tensor([[0.6578, 0.0677, 0.3761, 0.7128],
        [0.5043, 0.2732, 0.7933, 0.8344],
        [0.7068, 0.8613, 0.2280, 0.8588]])
tensor([[0.5414, 0.2525, 0.2491, 0.9383],
        [0.4913, 0.3907, 0.1270, 0.1318],
        [0.4268, 0.4062, 0.0053, 0.0891]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [35]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


---
As we can see manual_seed() changes seed only for the next random function. So we need to place manual_seed() function before every random function.

In [37]:
# Let's test it out
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (optional to upgrade as well)
2. Use  your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., this blog can be useful - https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computer on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation - https://pytorch.org/get-started/locally/

In [38]:
!nvidia-smi

Tue Mar 14 18:05:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:26:00.0  On |                  N/A |
| 46%   33C    P0    N/A /  75W |    600MiB /  4096MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default on CPU

In [7]:
# Check for GPU access with PyTorch

if torch.cuda.is_available():
    print('Yeah, your GPU is available!')
else:
    print('Sorry, you don\'t have access to your GPU')

Yeah, your GPU is available!


In [8]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [9]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [10]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [12]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [18]:
# If tensor is on GPU, can't transform it to NumPy
try:
    tensor_on_gpu.numpy()
except TypeError:
    print("ERROR: Can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.")

ERROR: Can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [21]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [23]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

### 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor - https://pytorch.org/docs/stable/tensors.html#torch-tensor and for torch.cuda - https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics.

### 2. Create a random tensor with shape (7, 7).

In [28]:
tensor_2 = torch.rand(7, 7)
print(f'Tensor with shape of 7x7:\n {tensor_2}')

Tensor with shape of 7x7:
 tensor([[0.5289, 0.1949, 0.5040, 0.9508, 0.9017, 0.5738, 0.2679],
        [0.5258, 0.9667, 0.2372, 0.3459, 0.9236, 0.6581, 0.8353],
        [0.4418, 0.2624, 0.2426, 0.6842, 0.7892, 0.6999, 0.5195],
        [0.4609, 0.3329, 0.3491, 0.6596, 0.2884, 0.0171, 0.5274],
        [0.9359, 0.6943, 0.2962, 0.1723, 0.0392, 0.3807, 0.2249],
        [0.3548, 0.5916, 0.3324, 0.8975, 0.9653, 0.4376, 0.1164],
        [0.6070, 0.4011, 0.4964, 0.3275, 0.4981, 0.4832, 0.9163]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [30]:
tensor_3 = torch.rand(1, 7)
print(f'Tensor_2:\n{tensor_2}\nTensor_3:\n{tensor_3}\nResult of Tensor_2 @ Tensor_3:\n{torch.matmul(tensor_2, tensor_3.T)}')

Tensor_2:
tensor([[0.5289, 0.1949, 0.5040, 0.9508, 0.9017, 0.5738, 0.2679],
        [0.5258, 0.9667, 0.2372, 0.3459, 0.9236, 0.6581, 0.8353],
        [0.4418, 0.2624, 0.2426, 0.6842, 0.7892, 0.6999, 0.5195],
        [0.4609, 0.3329, 0.3491, 0.6596, 0.2884, 0.0171, 0.5274],
        [0.9359, 0.6943, 0.2962, 0.1723, 0.0392, 0.3807, 0.2249],
        [0.3548, 0.5916, 0.3324, 0.8975, 0.9653, 0.4376, 0.1164],
        [0.6070, 0.4011, 0.4964, 0.3275, 0.4981, 0.4832, 0.9163]])
Tensor_3:
tensor([[0.3400, 0.3969, 0.9647, 0.9665, 0.2734, 0.5189, 0.3827]])
Result of Tensor_2 @ Tensor_3:
tensor([[2.3092],
        [2.0393],
        [1.9275],
        [1.5526],
        [1.3405],
        [2.0791],
        [1.8986]])


### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [33]:
torch.manual_seed(0)
tensor_2 = torch.rand(7, 7)
tensor_3 = torch.rand(1, 7)

print(f'Tensor_2:\n{tensor_2}\nTensor_3:\n{tensor_3}\nResult of Tensor_2 @ Tensor_3:\n{torch.matmul(tensor_2, tensor_3.T)}')


Tensor_2:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Tensor_3:
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
Result of Tensor_2 @ Tensor_3:
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [36]:
torch.cuda.manual_seed(1234)

tensor_GPU = torch.rand(7, 7, device='cuda')
tensor_GPU_2 = torch.rand(7, 7, device='cuda')

torch.cuda.manual_seed(1234)
tensor_GPU_3 = torch.rand(7, 7, device='cuda')

print(f'Tensor_GPU:\n{tensor_GPU}\nTensor_GPU_2:\n{tensor_GPU_2}\nTensor_GPU_3:\n{tensor_GPU_3}')


Tensor_GPU:
tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')
Tensor_GPU_2:
tensor([[0.6208, 0.0276, 0.3255, 0.1114, 0.6812, 0.3608, 0.1715],
        [0.1965, 0.8400, 0.0438, 0.3011, 0.0285, 0.1628, 0.6302],
        [0.0447, 0.0927, 0.5736, 0.1185, 0.8971, 0.0516, 0.7554],
        [0.2753, 0.1553, 0.3816, 0.0280, 0.6821, 0.0313, 0.5713],
        [0.8986, 0.7647, 0.4844, 0.3556, 0.2352, 0.2899, 0.7206],
        [0.3790, 0.2882, 0.1651, 0.4532, 0.1686, 0.9808, 0.3282],
        [0.5142, 0.2260, 0.2356, 0.7532, 0.7435, 0.8266, 0.5540]],
       device='cuda:0')


### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [41]:
torch.manual_seed(1234)
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)
print(f'Tensor_1:\n{tensor_1}\nTensor_2:\n{tensor_2}')

tensor_1 = tensor_1.to('cuda')
tensor_2 = tensor_2.to('cuda')

print(f'Tensor_1:\n{tensor_1}\nTensor_2:\n{tensor_2}')

# Less steps

torch.manual_seed(1234)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor_1 = torch.rand(2, 3).to('cuda')
tensor_2 = torch.rand(2, 3).to('cuda')

print(f'Tensor_1:\n{tensor_1}\nTensor_2:\n{tensor_2}')


Tensor_1:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Tensor_2:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
Tensor_1:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor_2:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
Tensor_1:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor_2:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [44]:
# Check shape of tensors in 6
print(f'Tensor_1 shape: {tensor_1.shape}\tTensor_2 shape: {tensor_2.shape}')

tensor_mul = torch.matmul(tensor_1, tensor_2.T)

print(f'Result of multiplication:\n{tensor_mul}')

Tensor_1 shape: torch.Size([2, 3])	Tensor_2 shape: torch.Size([2, 3])
Result of multiplication:
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find maximum value from 7.
max_value = tensor_mul.max()
# or
max_value = torch.max(tensor_mul)

# Find minimum value from 7.
min_value = tensor_mul.min()
# or
min_value = torch.min(tensor_mul)

print(f'Minimum value: {min_value}\nMaximum value: {max_value}')

Minimum value: 0.3647301495075226
Maximum value: 0.5617256760597229


### 9. Find the maximum and minimum index values of the output of 7.

In [49]:
# Find maximum value index from 7.
max_value_index = torch.argmax(tensor_mul)

# Find minimum value index from 7.
min_value_index = torch.argmin(tensor_mul)

print(f'Minimum value index: {min_value_index}\nMaximum value index: {max_value_index}')


Minimum value index: 0
Maximum value index: 3


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [53]:
big_tensor = torch.rand(size=(1,1,1,10))
print(f'This is our big tensor:\n{big_tensor}')

# Remove first dimensions
big_tensor_squeezed = big_tensor.squeeze()

print(f'Squeezed tensor:\n{big_tensor_squeezed}')


This is our big tensor:
tensor([[[[0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839, 0.8083,
           0.7528, 0.8988]]]])
Squeezed tensor:
tensor([0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839, 0.8083, 0.7528,
        0.8988])
